version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexagonal-api-node
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=products_db
      - REPOSITORY_TYPE=mysql
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - app-network
